### ISSUE TITLE
CSS is clean and succinct

### ISSUE THREAD

**Issue by ad3429** [mtubes/prj-rev-bwfs-tea-cozy#2]
https://github.com/mtubes/prj-rev-bwfs-tea-cozy/blob/master/teacozy/resources/css/style.css#L12-L123

Your CSS is short, clean and succinct -- good job! One area of improvement is to make sure to comment your stylings further so that when you come back to your code you remember exactly why you decided to style an element a particular way.

**Comment by mtubes** [comment]
Will do thanks! :)
