### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by ad3429** [mtubes/prj-rev-bwfs-tea-cozy#5]
**Summary Grade: Satisfactory**

Good job! Your files are organized nicely, and you did a great job of matching the client specification for the most part -- this is an important skill to have as a developer and you seem to understand that. Moreover, you generally followed excellent code practice, so make sure to keep that up!

I have made some comments in your code to take note of. One thing I noticed is that the content in the "Our Mission" section doesn't seem to be fully centered and stretched as the specification has it -- rather, it seems to be moved slightly to the left when I increase the browser width. Another thing I noticed is that you should try to comment your CSS stylings more extensively in future projects. 

This isn't a big issue now since you haven't learned about this yet, but I wanted to introduce you to the idea of responsive design. You will learn more about responsive design in the next project, but I wanted to provide a great resource to get you to start thinking about building sites that look good on all different kinds of platforms/browser sizes:

https://www.w3schools.com/css/css_responsive_intro.asp

Great job overall! As a further challenge, try using css to design your webpage even further! You did a great job in following the client specification, but for your own practice you should see how creative you can get by taking the design/styling of your site to the next level (for example, you can try experimenting with background colors on your other divs

**Comment by mtubes** [comment]
Thank you for the comment and suggestions! Have a wonderful day!
